"""
apps/capcut-v2/core/visual/models.py
Strongly typed data contracts for Phase A1 Visual Shot Planning.
"""
from __future__ import annotations

import enum
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any


class VisualBoundaryType(str, enum.Enum):
    """Classification of visual cut candidate origin."""
    SPEECH_START = "SPEECH_START"
    SUBTITLE_BOUNDARY = "SUBTITLE_BOUNDARY"
    PARAGRAPH_BOUNDARY = "PARAGRAPH_BOUNDARY"
    SENTENCE_BOUNDARY = "SENTENCE_BOUNDARY"
    CLAUSE_BOUNDARY = "CLAUSE_BOUNDARY"
    ACOUSTIC_PAUSE = "ACOUSTIC_PAUSE"
    DURATION_FORCED_INTERNAL_BOUNDARY = "DURATION_FORCED_INTERNAL_BOUNDARY"
    SPEECH_END = "SPEECH_END"
    MASTER_AUDIO_END = "MASTER_AUDIO_END"


class ImageSupplyState(str, enum.Enum):
    """Pacing signal derived from physical image supply vs speech duration."""
    SHORTAGE = "SHORTAGE"
    BALANCED = "BALANCED"
    SURPLUS = "SURPLUS"


class VisualPlannerEngine(str, enum.Enum):
    """Engine type for visual timeline shot generation."""
    LEGACY = "legacy"
    HIERARCHICAL_DP_V1 = "hierarchical_dp_v1"


@dataclass
class VisualBoundaryCandidate:
    """
    Candidate timeline cut boundary evaluated by the minimum-cost DP partitioner.
    Preserves underlying A0 structural metadata without modifying subtitle timing.
    """
    boundary_id: str
    timestamp_us: int
    timestamp_s: float
    boundary_type: VisualBoundaryType
    paragraph_ids: List[int] = field(default_factory=list)
    sentence_ids: List[int] = field(default_factory=list)
    source_token_left: Optional[str] = None
    source_token_right: Optional[str] = None
    left_cue_id: Optional[int] = None
    right_cue_id: Optional[int] = None
    acoustic_gap_ms: float = 0.0
    structural_strength: float = 0.0  # 0.0 (weak/mid-clause) to 1.0 (strong paragraph break)
    source_reason: str = ""
    is_internal: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "boundary_id": self.boundary_id,
            "timestamp_us": self.timestamp_us,
            "timestamp_s": round(self.timestamp_s, 3),
            "boundary_type": self.boundary_type.value,
            "paragraph_ids": self.paragraph_ids,
            "sentence_ids": self.sentence_ids,
            "source_token_left": self.source_token_left,
            "source_token_right": self.source_token_right,
            "left_cue_id": self.left_cue_id,
            "right_cue_id": self.right_cue_id,
            "acoustic_gap_ms": round(self.acoustic_gap_ms, 1),
            "structural_strength": round(self.structural_strength, 2),
            "source_reason": self.source_reason,
            "is_internal": self.is_internal,
        }


@dataclass
class ShotDurationPolicy:
    """Duration constraints for normal narration visual shots."""
    hard_min_s: float = 2.0
    soft_min_s: float = 3.0
    target_min_s: float = 4.0
    target_max_s: float = 6.5
    soft_max_s: float = 8.5
    hard_max_s: float = 12.0
    terminal_max_s: float = 14.0


@dataclass
class TailDurationPolicy:
    """Duration constraints for silent outro / tail shots."""
    hard_min_s: float = 4.0
    soft_min_s: float = 8.0
    target_min_s: float = 10.0
    target_max_s: float = 20.0
    soft_max_s: float = 25.0
    hard_max_s: float = 35.0


@dataclass
class VisualShot:
    """
    Individual visual shot generated by VisualShotPlanner and ImageAllocationPolicy.
    """
    shot_id: int
    start_us: int
    end_us: int
    duration_us: int
    image_id: str
    image_path: str
    cue_ids: List[int] = field(default_factory=list)
    paragraph_ids: List[int] = field(default_factory=list)
    sentence_ids: List[int] = field(default_factory=list)
    boundary_start_reason: str = ""
    boundary_end_reason: str = ""
    is_internal_split: bool = False
    reuse_count: int = 0
    previous_use_distance_us: Optional[int] = None
    motion_profile: Dict[str, Any] = field(default_factory=dict)
    planner_cost: float = 0.0
    diagnostics: Dict[str, Any] = field(default_factory=dict)

    @property
    def start_s(self) -> float:
        return self.start_us / 1_000_000.0

    @property
    def end_s(self) -> float:
        return self.end_us / 1_000_000.0

    @property
    def duration_s(self) -> float:
        return self.duration_us / 1_000_000.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "shot_id": self.shot_id,
            "start_us": self.start_us,
            "end_us": self.end_us,
            "duration_us": self.duration_us,
            "start_s": round(self.start_s, 3),
            "end_s": round(self.end_s, 3),
            "duration_s": round(self.duration_s, 3),
            "image_id": self.image_id,
            "image_path": self.image_path,
            "cue_ids": self.cue_ids,
            "paragraph_ids": self.paragraph_ids,
            "sentence_ids": self.sentence_ids,
            "boundary_start_reason": self.boundary_start_reason,
            "boundary_end_reason": self.boundary_end_reason,
            "is_internal_split": self.is_internal_split,
            "reuse_count": self.reuse_count,
            "previous_use_distance_us": self.previous_use_distance_us,
            "motion_profile": self.motion_profile,
            "planner_cost": round(self.planner_cost, 3),
            "diagnostics": self.diagnostics,
        }


@dataclass
class VisualPlannerOptions:
    """Runtime configuration for visual planning."""
    engine: VisualPlannerEngine = VisualPlannerEngine.LEGACY
    shadow_mode: bool = True
    duration_policy: ShotDurationPolicy = field(default_factory=ShotDurationPolicy)
    tail_policy: TailDurationPolicy = field(default_factory=TailDurationPolicy)
    min_reuse_distance_s: float = 60.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "engine": self.engine.value,
            "shadow_mode": self.shadow_mode,
            "duration_policy": asdict(self.duration_policy),
            "tail_policy": asdict(self.tail_policy),
            "min_reuse_distance_s": self.min_reuse_distance_s,
        }

